### ISSUE TITLE
Проверка установлено ли приложение

### ISSUE THREAD

**Issue by REDMONDS** [akeinhell/wot_clan#27]
Если приложение не установлено, то при переходе на главную страницу пишется ошибка в лог, что не может установить соединение с базой.

Насколько помню, проверка имеется, но не задействована.

**Comment by REDMONDS** [comment]
Uncaught Exception ActiveRecord\DatabaseException: "exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)'

**Comment by REDMONDS** [comment]
Работает :)
![xotbwl3](https://cloud.githubusercontent.com/assets/6460267/6523965/da60e12e-c405-11e4-9d60-ceda87c7a5ba.png)

**Comment by akeinhell** [comment]
@REDMONDS работает но через костыль )  не так хотелось бы
